const availableLangs = {
  'en': [
    'English', 
    [
      'Information is power. But like all power, there are those who want to keep it for themselves. The world\'s entire scientific and cultural heritage, published over centuries in books and journals, is increasingly being digitized and locked up by a handful of private corporations. Want to read the papers featuring the most famous results of the sciences? You\'ll need to send enormous amounts to publishers like Reed Elsevier.',
      'There are those struggling to change this. The Open Access Movement has fought valiantly to ensure that scientists do not sign their copyrights away but instead ensure their work is published on the Internet, under terms that allow anyone to access it. But even under the best scenarios, their work will only apply to things published in the future. Everything up until now will have been lost.',
      'That is too high a price to pay. Forcing academics to pay money to read the work of their colleagues? Scanning entire libraries but only allowing the folks at Google to read them?  Providing scientific articles to those at elite universities in the First World, but not to children in the Global South? It\'s outrageous and unacceptable.',
      '"I agree," many say, "but what can we do? The companies hold the copyrights, they make enormous amounts of money by charging for access, and it\'s perfectly legal — there\'s nothing we can do to stop them." But there is something we can, something that\'s already being done: we can fight back.',
      'Those with access to these resources — students, librarians, scientists — you have been given a privilege. You get to feed at this banquet of knowledge while the rest of the world is locked out. But you need not — indeed, morally, you cannot — keep this privilege for yourselves. You have a duty to share it with the world. And you have: trading passwords with colleagues, filling download requests for friends.',
      'Meanwhile, those who have been locked out are not standing idly by. You have been sneaking through holes and climbing over fences, liberating the information locked up by the publishers and sharing them with your friends.',
      'But all of this action goes on in the dark, hidden underground. It\'s called stealing or piracy, as if sharing a wealth of knowledge were the moral equivalent of plundering a ship and murdering its crew. But sharing isn\'t immoral — it\'s a moral imperative. Only those blinded by greed would refuse to let a friend make a copy.',
      'Large corporations, of course, are blinded by greed. The laws under which they operate require it — their shareholders would revolt at anything less. And the politicians they have bought off back them, passing laws giving them the exclusive power to decide who can make copies.',
      'There is no justice in following unjust laws. It\'s time to come into the light and, in the grand tradition of civil disobedience, declare our opposition to this private theft of public culture.',
      'We need to take information, wherever it is stored, make our copies and share them with the world. We need to take stuff that\'s out of copyright and add it to the archive. We need to buy secret databases and put them on the Web. We need to download scientific journals and upload them to file sharing networks. We need to fight for Guerilla Open Access.',
      'With enough of us, around the world, we\'ll not just send a strong message opposing the privatization of knowledge — we\'ll make it a thing of the past. Will you join us?',
      'Aaron Swartz',
      'July 2008, Eremo, Italy'
    ]
  ], 
  'es-ES': [
    'Español', 
    [
      'La información es poder. Pero como todo poder, hay quienes quieren quedarse con él. Todo el patrimonio cultural y científico del mundo, publicado durante siglos en libros y diarios, continúa siendo digitalizado y guardado por un puñado de corporaciones privadas. ¿Quieres leer publicaciones acerca de los más famosos resultados de la ciencia? Necesitarás enviar grandes cantidades a editoriales como Reed Elsevier.',
      'Existen personas luchando para cambiar esto. El Movimiento para el Acceso Abierto ha luchado valientemente para asegurar que los científicos no firmen derechos de autor y en cambio se aseguren que su trabajo sea publicado en Internet, bajo términos que permitan que cualquier persona tenga acceso a este. Pero incluso en el mejor de los casos, su lucha solamente aplicará para cosas que se publiquen en el futuro. El resto, lo publicado hasta ahora, se habrá perdido.',
      'Este es un precio demasiado alto para pagar. ¿Obligar a que académicos paguen dinero para leer el trabajo de sus colegas? ¿Digitalizar bibliotecas enteras pero solo permitir que la gente en Google las pueda leer? ¿Proveer artículos científicos a aquellos en las élites universitarias del primer mundo, pero no a niños en el sur del planeta? Es indignante e inaceptable.',
      '"Estoy de acuerdo", muchos dicen, "pero ¿qué podemos hacer? Las compañías mantienen los derechos de autor, ganan enormes cantidades de dinero al cobrar por el acceso, y todo es perfectamente legal. No hay nada que podamos hacer para detenerlas". Pero sí hay algo que podemos hacer, algo que ya se está haciendo: podemos contraatacar.',
      'Quienes tienen acceso a estos recursos -estudiantes, bibliotecarios, científicos- han recibido un privilegio. Pueden alimentarse de este banquete de conocimiento mientras el resto del mundo es excluido. Pero ustedes no necesitan -de hecho, moralmente, no pueden- mantener este privilegio solamente para ustedes. Tienen el deber de compartirlo con el mundo. Y tienen que compartir claves con sus colegas y llenar solicitudes de descargas para sus amigos.',
      'Mientras tanto, aquellos que han sido excluidos no esperan sin hacer nada. Han estado fisgoneando a través de agujeros y trepando cercas, liberando información guardada por las editoriales y compartiéndola con sus amigos.',
      'Pero todas estas acciones se quedan en la oscuridad, escondidas en el sótano. Se las llama robo o piratería, como si compartir la riqueza del conocimiento fuese el equivalente moral a saquear un barco y asesinar a su tripulación. Compartir no es inmoral: es un imperativo moral. Solo quienes están cegados por la ambición podrían rehusarse a dejar que un amigo obtenga una copia.',
      'Las grandes corporaciones, por supuesto, están cegadas por la ambición. Las leyes bajo las cuales operan lo requieren. Sus accionistas se sublevarían si fuese menos que esto. Y los políticos que han comprado las respaldan, aprobando leyes que les conceden el poder exclusivo para decidir quiénes pueden hacer copias.',
      'No hay justicia al cumplir leyes injustas. Es hora de salir a la luz y, siguiendo la tradición de la desobediencia civil, oponernos a este robo privado de la cultura pública.',
      'Necesitamos tomar la información, donde quiera que esté almacenada, hacer copias y compartirlas con el mundo. Necesitamos tomar cosas que ya no tienen derechos de autor y agregarlas al archivo. Necesitamos comprar bases de datos secretas y publicarlas en la web. Necesitamos descargar publicaciones científicas y subirlas a redes de intercambio de archivos. Necesitamos combatir en la Guerrilla del Acceso Abierto.',
      'Con suficientes de nosotros, alrededor del mundo, no solo enviaremos un mensaje firme en contra de la privatización del conocimiento. Haremos que sea una cosa del pasado.',
      '¿Te unirás a nosotros?',
      'Aaron Swartz',
      'Julio de 2008, Eremo, Italia'
    ]
  ],
  'fr': [
    'Français', 
    [
      'L’information, c’est le pouvoir. Mais comme pour tout pouvoir, il y a ceux qui veulent le garder pour eux. Le patrimoine culturel et scientifique mondial, publié depuis plusieurs siècles dans les livres et les revues, est de plus en plus souvent numérisé puis verrouillé par une poignée d’entreprises privées. Vous voulez lire les articles présentant les plus célèbres résultats scientifiques? Il vous faudra payer de grosses sommes à des éditeurs comme Reed Elsevier.',
      'Et il y a ceux qui luttent pour que cela change. Le mouvement pour le libre accès s’est vaillamment battu pour s’assurer que les scientifiques ne mettent pas toutes leurs publications sous copyright et s’assurer plutôt que leurs travaux seront publiés sur Internet sous des conditions qui en permettent l’accès à tous. Mais, même dans le scénario le plus optimiste, la politique de libre accès ne concerne que les publications futures. Tout ce qui a été fait jusqu’à présent est perdu.',
      'C’est trop cher payé. Contraindre les universitaires à débourser de l’argent pour lire le travail de leurs collègues ? Numériser des bibliothèques entières mais ne permettre qu’aux gens de chez Google de les lire ? Fournir des articles scientifiques aux chercheurs des plus grandes universités des pays riches, mais pas aux enfants des pays du Sud ? C’est scandaleux et inacceptable.',
      'Nombreux sont ceux qui disent: «Je suis d’accord mais que peut-on y faire? Les entreprises possèdent les droits de reproduction de ces documents, elles gagnent énormément d’argent en faisant payer l’accès, et c’est parfaitement légal, il n’y a rien que l’on puisse faire pour les en empêcher.» Mais si, on peut faire quelque chose, ce qu’on est déjà en train de faire: riposter.',
      'Vous qui avez accès à ces ressources, étudiants, bibliothécaires, scientifiques, on vous a donné un privilège. Vous pouvez vous nourrir au banquet de la connaissance pendant que le reste du monde en est exclu. Mais vous n’êtes pas obligés — moralement, vous n’en avez même pas le droit — de conserver ce privilège pour vous seuls. Il est de votre devoir de le partager avec le monde. Et c’est ce que vous avez fait: en échangeant vos mots de passe avec vos collègues, en remplissant des formulaires de téléchargement pour vos amis.',
      'Pendant ce temps, ceux qui ont été écartés de ce festin n’attendent pas sans rien faire. Vous vous êtes faufilés dans les brèches et avez escaladé les barrières, libérant l’information verrouillée par les éditeurs pour la partager avec vos amis.',
      'Mais toutes ces actions se déroulent dans l’ombre, de façon souterraine. On les qualifie de «vol» ou bien de « piratage », comme si partager une abondance de connaissances était moralement équivalent à l’abordage d’un vaisseau et au meurtre de son équipage. Mais le partage n’est pas immoral, c’est un impératif moral. Seuls ceux qu’aveugle la cupidité refusent une copie à leurs amis.',
      'Les grandes multinationales, bien sûr, sont aveuglées par la cupidité. Les lois qui les gouvernent l’exigent, leurs actionnaires se révolteraient à la moindre occasion. Et les politiciens qu’elles ont achetés les soutiennent en votant des lois qui leur donnent le pouvoir exclusif de décider qui est en droit de faire des copies.',
      'La justice ne consiste pas à se soumettre à des lois injustes. Il est temps de sortir de l’ombre et, dans la grande tradition de la désobéissance civile, d’affirmer notre opposition à la confiscation criminelle de la culture publique.',
      'Nous avons besoin de récolter l’information où qu’elle soit stockée, d’en faire des copies et de la partager avec le monde. Nous devons nous emparer du domaine public et l’ajouter aux archives. Nous devons acheter des bases de données secrètes et les mettre sur le Web. Nous devons télécharger des revues scientifiques et les poster sur des réseaux de partage de fichiers. Nous devons mener le combat de la guérilla pour le libre accès.',
      'Lorsque nous serons assez nombreux de par le monde, nous n’enverrons pas seulement un puissant message d’opposition à la privatisation de la connaissance: nous ferons en sorte que cette privatisation appartienne au passé. Serez-vous des nôtres?',
      'Aaron Swartz Juillet 2008, Eremo, Italie'
    ]
  ],
  'it': [
    'Italiano', 
    [
      'L’informazione è potere. Ma come con ogni tipo di potere, ci sono quelli che se ne vogliono impadronire. L’intero patrimonio scientifico e culturale, pubblicato nel corso dei secoli in libri e riviste, è sempre più digitalizzato e tenuto sotto chiave da una manciata di società private. Vuoi leggere le riviste che ospitano i più famosi risultati scientifici? Dovrai pagare enormi somme ad editori come Reed Elsevier.',
      'C’è chi lotta per cambiare tutto questo. Il movimento Open Access ha combattuto valorosamente perché gli scienziati non cedano i loro diritti d’autore e che invece il loro lavoro sia pubblicato su Internet, a condizioni che consentano l’accesso a tutti. Ma anche nella migliore delle ipotesi, il loro lavoro varrà solo per le cose pubblicate in futuro. Tutto ciò che è stato pubblicato fino ad oggi sarà perduto.',
      'Questo è un prezzo troppo alto da pagare. Forzare i ricercatori a pagare per leggere il lavoro dei loro colleghi? Scansionare intere biblioteche, ma consentire solo alla gente che lavora per Google di leggerne i libri? Fornire articoli scientifici alle università d’élite del Primo Mondo, ma non ai bambini del Sud del Mondo? Tutto ciò è oltraggioso ed inaccettabile.',
      '“Sono d’accordo,” dicono in molti, “ma cosa possiamo fare? Le società detengono i diritti d’autore, guadagnano enormi somme di denaro facendo pagare l’accesso, ed è tutto perfettamente legale — non c’è niente che possiamo fare per fermarli”. Ma qualcosa che possiamo fare c’è, qualcosa che è già stato fatto: possiamo contrattaccare.',
      'Tutti voi, che avete accesso a queste risorse, studenti, bibliotecari o scienziati, avete ricevuto un privilegio: potete nutrirvi al banchetto della conoscenza mentre il resto del mondo rimane chiuso fuori. Ma non dovete — anzi, moralmente, non potete — conservare questo privilegio solo per voi, avete il dovere di condividerlo con il mondo. Avete il dovere di scambiare le password con i colleghi e scaricare gli articoli per gli amici.',
      'Tutti voi che siete stati chiusi fuori non starete a guardare, nel frattempo. Vi intrufolerete attraverso i buchi, scavalcherete le recinzioni, e libererete le informazioni che gli editori hanno chiuso e le condividerete con i vostri amici.',
      'Ma tutte queste azioni sono condotte nella clandestinità oscura e nascosta. Sono chiamate “furto” o “pirateria”, come se condividere conoscenza fosse l’equivalente morale di saccheggiare una nave ed assassinarne l’equipaggio, ma condividere non è immorale — è un imperativo morale. Solo chi fosse accecato dall’avidità rifiuterebbe di concedere una copia ad un amico.',
      'E le grandi multinazionali, ovviamente, sono accecate dall’avidità. Le stesse leggi a cui sono sottoposte richiedono che siano accecate dall’avidità — se così non fosse i loro azionisti si rivolterebbero. E i politici, corrotti dalle grandi aziende, le supportano approvando leggi che danno loro il potere esclusivo di decidere chi può fare copie.',
      'Non c’è giustizia nel rispettare leggi ingiuste. È tempo di uscire allo scoperto e, nella grande tradizione della disobbedienza civile, dichiarare la nostra opposizione a questo furto privato della cultura pubblica.',
      'Dobbiamo acquisire le informazioni, ovunque siano archiviate, farne copie e condividerle con il mondo. Dobbiamo prendere ciò che è fuori dal diritto d’autore e caricarlo su Internet Archive. Dobbiamo acquistare banche dati segrete e metterle sul web. Dobbiamo scaricare riviste scientifiche e caricarle sulle reti di condivisione. Dobbiamo lottare per la Guerrilla Open Access.',
      'Se in tutto il mondo saremo in numero sufficiente, non solo manderemo un forte messaggio contro la privatizzazione della conoscenza, ma la renderemo un ricordo del passato.',
      'Vuoi essere dei nostri?',
      'Aaron Swartz Luglio 2008, Eremo, Italia'
    ]
  ],
  'de': [
    'Deutsche',
    [
      'Information ist Macht. Und wie bei jeglicher Macht gibt es jene, die sie für sich behalten wollen. Das komplette wissenschaftliche und kulturelle Erbe der Welt, über Jahrhunderte in Büchern und Fachzeitschriften veröffentlicht, wird mehr und mehr von einer Handvoll privater Konzerne digitalisiert und weggeschlossen. Möchtest du die Papers mit den bekanntesten wissenschaftlichen Ergebnissen lesen? Dann musst du enorme Summen an Verleger wie Reed Elsevier senden.',
      'Einige Leute wehren sich, um dies zu ändern. Die Open-Access-Bewegung kämpfte tapfer um dafür zu sorgen, dass Wissenschaftler ihre Urheberrechte nicht abgeben, sondern stattdessen sicherstellen, dass ihre Arbeit im Internet veröffentlicht ist, unter Bedingungen, die jedem darauf Zugriff erlauben. Aber selbst im besten Fall wird sich ihre Arbeit nur auf zukünftig veröffentliche Werke auswirken. Alles vor dem jetzigen Zeitpunkt wird verloren sein.',
      'Dieser Preis ist zu hoch. Akademiker zwingen, für das Lesen der Arbeiten ihrer Kollegen Geld zu bezahlen? Komplette Bibliotheken scannen, aber nur Google-Angestellten erlauben, sie zu lesen? Studenten von Elite-Universitäten der Ersten Welt wissenschaftliche Artikel bereitstellen, aber nicht für Kinder im globalen Süden? Es ist abscheulich und inakzeptabel.',
      '»Ich stimme zu,« sagen viele, »aber was können wir tun? Den Firmen gehören die Urheberrechte, sie machen durch die Zugriffsgebühren enorm viel Geld, und alles ist vollkommen legal – wir können nichts tun, um sie zu stoppen.« Aber wir können etwas tun, etwas was bereits getan wird: Wir können zurückschlagen.',
      'All jene, die Zugriff auf diese Ressourcen haben – Studenten, Bibliothekare, Wissenschaftler – euch wurde ein Privileg gegeben. Ihr könnt an diesem Bankett des Wissens speisen, während der Rest der Welt ausgesperrt ist. Aber ihr müsst dieses Privileg nicht – tatsächlich könnt ihr es moralisch nicht – für euch selber behalten. Ihr steht in der Pflicht, es mit der Welt zu teilen. Und ihr macht es bereits: Passwörter an Kollegen weitergeben, Sachen für Freunde herunterladen.',
      'Währenddessen bleiben die Ausgesperrten nicht einfach untätig. Ihr seid durch Löcher geschlüpft und über Zäune geklettert, habt die von Verlegern weggeschlossene Information befreit und sie mit euren Freunden geteilt.',
      'Aber all dies läuft im Dunkeln ab, versteckt im Untergrund. Es wird Diebstahl und Raubkopieren genannt, als ob das Teilen eines Wissensschatzes das morale Äquivalent zu einer Schiffsplünderung und Ermordung der Crew wären. Aber Teilen ist nicht unmoralisch – es ist ein moralischer Imperativ. Nur jene von Habgier geblendeten würden einem Freund verweigern, eine Kopie zu erstellen.',
      'Große Konzerne sind natürlich von Habgier geblendet. Das ist bedingt durch die Gesetze, unter denen sie agieren – ihre Shareholder würden sich mit weniger nicht zufrieden geben. Und ihre gekauften Politiker verteidigen sie; erlassen Gesetze, welche ihnen die exklusive Entscheidungsmacht geben, wer Kopien anfertigen darf.',
      'Es ist keine Gerechtigkeit, ungerechte Gesetze zu befolgen. Es ist Zeit, ins Licht zu gehen und, in der großen Tradition zivilen Ungehorsams, unseren Widerstand gegen diesen kulturellen Diebstahl an der Öffentlichkeit zu verkünden.',
      'Wir müssen Information nehmen, egal wo sie gespeichert ist, unsere Kopien machen und diese mit der Welt teilen. Wir müssen Sachen nehmen, deren Urheberrecht abgelaufen ist und es zum Archiv hinzufügen. Wir müssen geheime Datenbanken kaufen und diese online stellen. Wir müssen wissenschaftliche Fachzeitschriften herunterladen und sie auf File-Sharing-Seiten hochladen. Wir müssen für Guerilla Open Access kämpfen.',
      'Mit genügend von uns, weltweit, werden wir nicht nur eine starke Botschaft gegen die Privatisierung von Wissen senden – wir werden es vollständig abschaffen. Wirst du dich uns anschließen?',
      'Aaron Swartz',
      'Juli 2008, Eremo, Italien'
    ]
  ]
};

// ordering languages alphabetically
let langs = Object.keys(availableLangs).sort().reduce(
  (obj, key) => {
    obj[key] = availableLangs[key];
    return obj;
  }, {}
);

/*
const langCodes = {
  "af":    "Afrikaans",
  "sq":    "Albanian",
  "an":    "Aragonese",
  "ar":    "Arabic (Standard)",
  "ar-dz": "Arabic (Algeria)",
  "ar-bh": "Arabic (Bahrain)",
  "ar-eg": "Arabic (Egypt)",
  "ar-iq": "Arabic (Iraq)",
  "ar-jo": "Arabic (Jordan)",
  "ar-kw": "Arabic (Kuwait)",
  "ar-lb": "Arabic (Lebanon)",
  "ar-ly": "Arabic (Libya)",
  "ar-ma": "Arabic (Morocco)",
  "ar-om": "Arabic (Oman)",
  "ar-qa": "Arabic (Qatar)",
  "ar-sa": "Arabic (Saudi Arabia)",
  "ar-sy": "Arabic (Syria)",
  "ar-tn": "Arabic (Tunisia)",
  "ar-ae": "Arabic (U.A.E.)",
  "ar-ye": "Arabic (Yemen)",
  "hy":    "Armenian",
  "as":    "Assamese",
  "ast":   "Asturian",
  "az":    "Azerbaijani",
  "eu":    "Basque",
  "bg":    "Bulgarian",
  "be":    "Belarusian",
  "bn":    "Bengali",
  "bs":    "Bosnian",
  "br":    "Breton",
  "bg":    "Bulgarian",
  "my":    "Burmese",
  "ca":    "Catalan",
  "ch":    "Chamorro",
  "ce":    "Chechen",
  "zh":    "Chinese",
  "zh-hk": "Chinese (Hong Kong)",
  "zh-cn": "Chinese (PRC)",
  "zh-sg": "Chinese (Singapore)",
  "zh-tw": "Chinese (Taiwan)",
  "cv":    "Chuvash",
  "co":    "Corsican",
  "cr":    "Cree",
  "hr":    "Croatian",
  "cs":    "Czech",
  "da":    "Danish",
  "nl":    "Dutch (Standard)",
  "nl-be": "Dutch (Belgian)",
  "en":    "English",
  "en-au": "English (Australia)",
  "en-bz": "English (Belize)",
  "en-ca": "English (Canada)",
  "en-ie": "English (Ireland)",
  "en-jm": "English (Jamaica)",
  "en-nz": "English (New Zealand)",
  "en-ph": "English (Philippines)",
  "en-za": "English (South Africa)",
  "en-tt": "English (Trinidad & Tobago)",
  "en-gb": "English (United Kingdom)",
  "en-us": "English (United States)",
  "en-zw": "English (Zimbabwe)",
  "eo":    "Esperanto",
  "et":    "Estonian",
  "fo":    "Faeroese",
  "fa":    "Farsi",
  "fj":    "Fijian",
  "fi":    "Finnish",
  "fr":    "French (Standard)",
  "fr-be": "French (Belgium)",
  "fr-ca": "French (Canada)",
  "fr-fr": "French (France)",
  "fr-lu": "French (Luxembourg)",
  "fr-mc": "French (Monaco)",
  "fr-ch": "French (Switzerland)",
  "fy":    "Frisian",
  "fur":   "Friulian",
  "gd":    "Gaelic (Scots)",
  "gd-ie": "Gaelic (Irish)",
  "gl":    "Galacian",
  "ka":    "Georgian",
  "de":    "German (Standard)",
  "de-at": "German (Austria)",
  "de-de": "German (Germany)",
  "de-li": "German (Liechtenstein)",
  "de-lu": "German (Luxembourg)",
  "de-ch": "German (Switzerland)",
  "el":    "Greek",
  "gu":    "Gujurati",
  "ht":    "Haitian",
  "he":    "Hebrew",
  "hi":    "Hindi",
  "hu":    "Hungarian",
  "is":    "Icelandic",
  "id":    "Indonesian",
  "iu":    "Inuktitut",
  "ga":    "Irish",
  "it":    "Italian (Standard)",
  "it-ch": "Italian (Switzerland)",
  "ja":    "Japanese",
  "kn":    "Kannada",
  "ks":    "Kashmiri",
  "kk":    "Kazakh",
  "km":    "Khmer",
  "ky":    "Kirghiz",
  "tlh":   "Klingon",
  "ko":    "Korean",
  "ko-kp": "Korean (North Korea)",
  "ko-kr": "Korean (South Korea)",
  "la":    "Latin",
  "lv":    "Latvian",
  "lt":    "Lithuanian",
  "lb":    "Luxembourgish",
  "mk":    "FYRO Macedonian",
  "ms":    "Malay",
  "ml":    "Malayalam",
  "mt":    "Maltese",
  "mi":    "Maori",
  "mr":    "Marathi",
  "mo":    "Moldavian",
  "nv":    "Navajo",
  "ng":    "Ndonga",
  "ne":    "Nepali",
  "no":    "Norwegian",
  "nb":    "Norwegian (Bokmal)",
  "nn":    "Norwegian (Nynorsk)",
  "oc":    "Occitan",
  "or":    "Oriya",
  "om":    "Oromo",
  "fa":    "Persian",
  "fa-ir": "Persian/Iran",
  "pl":    "Polish",
  "pt":    "Portuguese",
  "pt-br": "Portuguese (Brazil)",
  "pa":    "Punjabi",
  "pa-in": "Punjabi (India)",
  "pa-pk": "Punjabi (Pakistan)",
  "qu":    "Quechua",
  "rm":    "Rhaeto-Romanic",
  "ro":    "Romanian",
  "ro-mo": "Romanian (Moldavia)",
  "ru":    "Russian",
  "ru-mo": "Russian (Moldavia)",
  "sz":    "Sami (Lappish)",
  "sg":    "Sango",
  "sa":    "Sanskrit",
  "sc":    "Sardinian",
  "gd":    "Scots Gaelic",
  "sd":    "Sindhi",
  "si":    "Singhalese",
  "sr":    "Serbian",
  "sk":    "Slovak",
  "sl":    "Slovenian",
  "so":    "Somani",
  "sb":    "Sorbian",
  "es":    "Spanish",
  "es-ar": "Spanish (Argentina)",
  "es-bo": "Spanish (Bolivia)",
  "es-cl": "Spanish (Chile)",
  "es-co": "Spanish (Colombia)",
  "es-cr": "Spanish (Costa Rica)",
  "es-do": "Spanish (Dominican Republic)",
  "es-ec": "Spanish (Ecuador)",
  "es-sv": "Spanish (El Salvador)",
  "es-gt": "Spanish (Guatemala)",
  "es-hn": "Spanish (Honduras)",
  "es-mx": "Spanish (Mexico)",
  "es-ni": "Spanish (Nicaragua)",
  "es-pa": "Spanish (Panama)",
  "es-py": "Spanish (Paraguay)",
  "es-pe": "Spanish (Peru)",
  "es-pr": "Spanish (Puerto Rico)",
  "es-es": "Spanish (Spain)",
  "es-uy": "Spanish (Uruguay)",
  "es-ve": "Spanish (Venezuela)",
  "sx":    "Sutu",
  "sw":    "Swahili",
  "sv":    "Swedish",
  "sv-fi": "Swedish (Finland)",
  "sv-sv": "Swedish (Sweden)",
  "ta":    "Tamil",
  "tt":    "Tatar",
  "te":    "Teluga",
  "th":    "Thai",
  "tig":   "Tigre",
  "ts":    "Tsonga",
  "tn":    "Tswana",
  "tr":    "Turkish",
  "tk":    "Turkmen",
  "uk":    "Ukrainian",
  "hsb":   "Upper Sorbian",
  "ur":    "Urdu",
  "ve":    "Venda",
  "vi":    "Vietnamese",
  "vo":    "Volapuk",
  "wa":    "Walloon",
  "cy":    "Welsh",
  "xh":    "Xhosa",
  "ji":    "Yiddish",
  "zu":    "Zulu",
};
*/