const en = [
  'Information is power. But like all power, there are those who want to keep it for themselves. The world\'s entire scientific and cultural heritage, published over centuries in books and journals, is increasingly being digitized and locked up by a handful of private corporations. Want to read the papers featuring the most famous results of the sciences? You\'ll need to send enormous amounts to publishers like Reed Elsevier.',
  'There are those struggling to change this. The Open Access Movement has fought valiantly to ensure that scientists do not sign their copyrights away but instead ensure their work is published on the Internet, under terms that allow anyone to access it. But even under the best scenarios, their work will only apply to things published in the future. Everything up until now will have been lost.',
  'That is too high a price to pay. Forcing academics to pay money to read the work of their colleagues? Scanning entire libraries but only allowing the folks at Google to read them?  Providing scientific articles to those at elite universities in the First World, but not to children in the Global South? It\'s outrageous and unacceptable.',
  '"I agree," many say, "but what can we do? The companies hold the copyrights, they make enormous amounts of money by charging for access, and it\'s perfectly legal — there\'s nothing we can do to stop them." But there is something we can, something that\'s already being done: we can fight back.',
  'Those with access to these resources — students, librarians, scientists — you have been given a privilege. You get to feed at this banquet of knowledge while the rest of the world is locked out. But you need not — indeed, morally, you cannot — keep this privilege for yourselves. You have a duty to share it with the world. And you have: trading passwords with colleagues, filling download requests for friends.',
  'Meanwhile, those who have been locked out are not standing idly by. You have been sneaking through holes and climbing over fences, liberating the information locked up by the publishers and sharing them with your friends.',
  'But all of this action goes on in the dark, hidden underground. It\'s called stealing or piracy, as if sharing a wealth of knowledge were the moral equivalent of plundering a ship and murdering its crew. But sharing isn\'t immoral — it\'s a moral imperative. Only those blinded by greed would refuse to let a friend make a copy.',
  'Large corporations, of course, are blinded by greed. The laws under which they operate require it — their shareholders would revolt at anything less. And the politicians they have bought off back them, passing laws giving them the exclusive power to decide who can make copies.',
  'There is no justice in following unjust laws. It\'s time to come into the light and, in the grand tradition of civil disobedience, declare our opposition to this private theft of public culture.',
  'We need to take information, wherever it is stored, make our copies and share them with the world. We need to take stuff that\'s out of copyright and add it to the archive. We need to buy secret databases and put them on the Web. We need to download scientific journals and upload them to file sharing networks. We need to fight for Guerilla Open Access.',
  'With enough of us, around the world, we\'ll not just send a strong message opposing the privatization of knowledge — we\'ll make it a thing of the past. Will you join us?',
  'Aaron Swartz',
  'July 2008, Eremo, Italy'
  ];
  
const es = [
  'La información es poder. Pero como todo poder, hay quienes quieren quedarse con él. Todo el patrimonio cultural y científico del mundo, publicado durante siglos en libros y diarios, continúa siendo digitalizado y guardado por un puñado de corporaciones privadas. ¿Quieres leer publicaciones acerca de los más famosos resultados de la ciencia? Necesitarás enviar grandes cantidades a editoriales como Reed Elsevier.',
  'Existen personas luchando para cambiar esto. El Movimiento para el Acceso Abierto ha luchado valientemente para asegurar que los científicos no firmen derechos de autor y en cambio se aseguren que su trabajo sea publicado en Internet, bajo términos que permitan que cualquier persona tenga acceso a este. Pero incluso en el mejor de los casos, su lucha solamente aplicará para cosas que se publiquen en el futuro. El resto, lo publicado hasta ahora, se habrá perdido.',
  'Este es un precio demasiado alto para pagar. ¿Obligar a que académicos paguen dinero para leer el trabajo de sus colegas? ¿Digitalizar bibliotecas enteras pero solo permitir que la gente en Google las pueda leer? ¿Proveer artículos científicos a aquellos en las élites universitarias del primer mundo, pero no a niños en el sur del planeta? Es indignante e inaceptable.',
  '"Estoy de acuerdo", muchos dicen, "pero ¿qué podemos hacer? Las compañías mantienen los derechos de autor, ganan enormes cantidades de dinero al cobrar por el acceso, y todo es perfectamente legal. No hay nada que podamos hacer para detenerlas". Pero sí hay algo que podemos hacer, algo que ya se está haciendo: podemos contraatacar.',
  'Quienes tienen acceso a estos recursos -estudiantes, bibliotecarios, científicos- han recibido un privilegio. Pueden alimentarse de este banquete de conocimiento mientras el resto del mundo es excluido. Pero ustedes no necesitan -de hecho, moralmente, no pueden- mantener este privilegio solamente para ustedes. Tienen el deber de compartirlo con el mundo. Y tienen que compartir claves con sus colegas y llenar solicitudes de descargas para sus amigos.',
  'Mientras tanto, aquellos que han sido excluidos no esperan sin hacer nada. Han estado fisgoneando a través de agujeros y trepando cercas, liberando información guardada por las editoriales y compartiéndola con sus amigos.',
  'Pero todas estas acciones se quedan en la oscuridad, escondidas en el sótano. Se las llama robo o piratería, como si compartir la riqueza del conocimiento fuese el equivalente moral a saquear un barco y asesinar a su tripulación. Compartir no es inmoral: es un imperativo moral. Solo quienes están cegados por la ambición podrían rehusarse a dejar que un amigo obtenga una copia.',
  'Las grandes corporaciones, por supuesto, están cegadas por la ambición. Las leyes bajo las cuales operan lo requieren. Sus accionistas se sublevarían si fuese menos que esto. Y los políticos que han comprado las respaldan, aprobando leyes que les conceden el poder exclusivo para decidir quiénes pueden hacer copias.',
  'No hay justicia al cumplir leyes injustas. Es hora de salir a la luz y, siguiendo la tradición de la desobediencia civil, oponernos a este robo privado de la cultura pública.',
  'Necesitamos tomar la información, donde quiera que esté almacenada, hacer copias y compartirlas con el mundo. Necesitamos tomar cosas que ya no tienen derechos de autor y agregarlas al archivo. Necesitamos comprar bases de datos secretas y publicarlas en la web. Necesitamos descargar publicaciones científicas y subirlas a redes de intercambio de archivos. Necesitamos combatir en la Guerrilla del Acceso Abierto.',
  'Con suficientes de nosotros, alrededor del mundo, no solo enviaremos un mensaje firme en contra de la privatización del conocimiento. Haremos que sea una cosa del pasado.',
  '¿Te unirás a nosotros?',
  'Aaron Swartz',
  'Julio de 2008, Eremo, Italia'
];

  